In [9]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

### Class
- PARENT -> CHILD class 상속
- torch.nn.Module를 항상 부모 클래스로 상속 받을 것 -> 학습에 관련된 method들을 사용할 수 있음


In [5]:
from typing import Any


class Parent():
    def __init__(self,name):
        self.name = name
        
    def call_name(self):
        print(f"my name is {self.name}")
        
    def __call__(self):
        self.call_name()
        
class Child(Parent):
    
    def __init__(self,name):
        super().__init__(name)
        self.name = name
    def call_name(self):
        print(f"my name is {self.name} and I am child")
        
        
a = Child("jiwon") # 상속 받았기 때문에 부모의 __call__ 호출
a()

my name is jiwon and I am child


### Transformer

#### Layer Normalization

In [6]:
x = np.random.randint(0,10,(2,3))
x

array([[1, 2, 1],
       [3, 3, 8]])

In [14]:
x.mean(axis=-1, keepdims=True)

array([[1.33333333],
       [4.66666667]])

In [8]:
x.std(axis=-1)

array([0.47140452, 2.3570226 ])

In [40]:
hi = torch.zeros(256)
print(hi)
hi2 = torch.randn(2,2)
print(hi2)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [35]:
class LayerNorm(nn.Module):
    
    def __init__(self,features,eps=1e-6):
        super(LayerNorm,self).__init__()
        self.a2 = nn.Parameter(torch.ones(features))
        self.b2 = nn.Parameter(torch.zeros(features))
        self.eps = eps
        
    def forward(self,x):
        x = x.float()
        mean = x.mean(-1,keepdim=True)
        print('mean',mean.shape)
        x = (x-mean)/(x.std(-1,keepdim=True)+self.eps)
        print('x'  ,x.shape)
        print('b',self.b2.shape)
        x= self.a2 * x + self.b2
        return x

In [49]:
layer_norm = LayerNorm(256)

a = torch.randn(1,2,1)
print(a.shape)
b = layer_norm(a)

print(b)

torch.Size([1, 2, 1])
mean torch.Size([1, 2, 1])
x torch.Size([1, 2, 1])
b torch.Size([256])
tensor([[[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
          nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
          nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
          nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
          nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
          nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
          nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
          nan, nan, nan, nan, na

In [24]:
a

LayerNorm()